# Generated by Django 3.1.1 on 2020-09-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('', ''), ('Animals', 'Animals'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Housing', 'Housing'), ('Media', 'Media'), ('Services', 'Services'), ('Sports', 'Sports')], max_length=64, null=True),
        ),
    ]
